name: action-on-push

on:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install packajes
        run: npm i

      - name: run eslint
        run: make lint
